/**
 * GitWorktreeManager type definitions.
 *
 * Provides isolated git worktree environments for sub-agents spawned by the
 * OrchestratorAgent.  Each worktree is an independent checkout on its own
 * branch — sub-agents can make file changes without stepping on each other,
 * and results can be merged back when the node completes.
 */

import type { Logger } from "../logging/logger";

// ─── Error Types ────────────────────────────────────────────────────────────

/**
 * Machine-readable error codes produced by GitWorktreeManager operations.
 */
export type GitWorktreeErrorCode =
  | "GIT_NOT_FOUND"
  | "WORKTREE_CREATE_FAILED"
  | "WORKTREE_REMOVE_FAILED"
  | "WORKTREE_NOT_FOUND"
  | "WORKTREE_DIRTY"
  | "MERGE_CONFLICT"
  | "BRANCH_EXISTS"
  | "PERMISSION_DENIED"
  | "INVALID_CONFIG";

/**
 * Thrown when a git worktree operation fails.
 *
 * The `code` property lets callers branch on the failure reason without
 * parsing error messages.  `worktreeId` identifies the failing worktree
 * when applicable (e.g. during remove).
 */
export class GitWorktreeError extends Error {
  public readonly code: GitWorktreeErrorCode;
  public readonly worktreeId?: string;

  constructor(
    message: string,
    code: GitWorktreeErrorCode,
    worktreeId?: string,
  ) {
    super(message);
    this.name = "GitWorktreeError";
    this.code = code;
    this.worktreeId = worktreeId;
  }
}

// ─── Configuration ──────────────────────────────────────────────────────────

/**
 * Configuration for GitWorktreeManager.
 */
export interface GitWorktreeConfig {
  /**
   * Absolute path to the main git repository root.
   * Must be an existing directory with a `.git` folder.
   */
  repoPath: string;

  /**
   * Parent directory where worktrees are created.
   * Default: `<repoPath>/.kagent-worktrees/`
   */
  worktreesDir?: string;

  /**
   * Default base ref for new worktrees (branch, tag, or commit).
   * Default: "HEAD"
   */
  defaultBaseRef?: string;

  /** Logger instance for framework-internal messages. */
  logger?: Logger;

  /**
   * Prefix for auto-generated worktree branch names.
   * Default: "kagent"
   */
  branchPrefix?: string;

  /**
   * Whether to auto-remove worktrees after their operation completes.
   * When true, removeWorktree is called as soon as a node finishes.
   * Default: true.
   */
  autoCleanup?: boolean;
}

// ─── Worktree Info & Status ─────────────────────────────────────────────────

/**
 * Lifecycle status of a worktree.
 */
export type WorktreeStatus = "active" | "completed" | "failed";

/**
 * Metadata record for a managed worktree.
 *
 * `id` is the manager-assigned unique identifier.  `path` is the absolute
 * path on disk.  `nodeId` (when set) correlates this worktree to an
 * OrchestratorAgent TaskNode.
 */
export interface WorktreeInfo {
  /** Unique identifier generated by the manager. */
  id: string;

  /** Full absolute path to the worktree directory on disk. */
  path: string;

  /** The git branch created for this worktree. */
  branchName: string;

  /** The base ref from which this worktree was created. */
  baseRef: string;

  /** Associated TaskNode ID (for orchestration correlation). */
  nodeId?: string;

  /** ISO-8601 timestamp of creation. */
  createdAt: string;

  /** Current lifecycle status. */
  status: WorktreeStatus;

  /** Whether the worktree has uncommitted changes (checked via `git status`). */
  isDirty: boolean;

  /** Arbitrary consumer metadata. */
  metadata?: Record<string, string>;
}

// ─── Create / Remove Options ────────────────────────────────────────────────

/**
 * Options for `GitWorktreeManager.createWorktree()`.
 */
export interface CreateWorktreeOptions {
  /**
   * Branch name for the new worktree.
   * Auto-generated from `branchPrefix` + `nodeId` if omitted.
   */
  branchName?: string;

  /**
   * Base ref to create from (overrides config.defaultBaseRef).
   */
  baseRef?: string;

  /** Associated TaskNode ID. */
  nodeId?: string;

  /** Arbitrary metadata stored on the WorktreeInfo. */
  metadata?: Record<string, string>;
}

/**
 * Options for `GitWorktreeManager.removeWorktree()`.
 */
export interface RemoveWorktreeOptions {
  /**
   * Force removal even if the worktree has uncommitted changes.
   * Default: false.
   */
  force?: boolean;

  /**
   * Merge the worktree's branch back into the base ref before removal.
   * Default: false.
   */
  mergeBack?: boolean;

  /**
   * Target branch for merge (defaults to the baseRef the worktree
   * was created from).
   */
  mergeTarget?: string;

  /**
   * Whether to delete the worktree's branch after removal.
   * Default: false.
   */
  deleteBranch?: boolean;

  /**
   * Push the branch to remote after merge.  Only meaningful when
   * `mergeBack` is also true.
   * Default: false.
   */
  pushAfterMerge?: boolean;
}

// ─── Status Result ─────────────────────────────────────────────────────────

/**
 * Detailed status returned by `getWorktreeStatus()`.
 */
export interface WorktreeStatusResult {
  /** Whether the worktree directory exists on disk. */
  exists: boolean;

  /** Worktree metadata if it exists and is tracked. */
  info?: WorktreeInfo;

  /** Whether the associated git branch still exists. */
  branchExists: boolean;

  /** Whether the worktree has uncommitted changes. */
  isDirty: boolean;

  /** Full `git status` output. */
  gitStatus: string;
}

// ─── Session Persistence ────────────────────────────────────────────────────

/**
 * Serializable worktree state for session checkpoints.
 */
export interface WorktreeSessionState {
  /** All worktrees tracked during this session with current statuses. */
  worktrees: WorktreeInfo[];
}
