import * as fs from "fs";
import * as path from "path";
import { AgentHooks } from "../core/hooks";
import { LLMResponse } from "../llm/interface";
import { LLMNetworkError } from "../llm/errors";
import { MessageData } from "../messages/types";
import { Tool } from "../tools/types";
import { AgentTraceEvent, AgentTraceEventType } from "./types";
import { Logger, ConsoleLogger } from "../logging/logger";

/**
 * Configuration for the TraceLogger.
 */
export interface TraceLoggerConfig {
  /**
   * Session identifier used in the trace file name.
   * Defaults to `trace-<timestamp>-<random>`.
   */
  sessionId?: string;

  /**
   * Output directory for trace HTML files.
   * Defaults to `.kagent-traces/`.
   */
  outputDir?: string;

  /**
   * Optional agent label shown in the trace report header.
   */
  agentLabel?: string;

  /**
   * Optional model name shown in the trace report header.
   */
  modelName?: string;

  /** Logger instance (defaults to ConsoleLogger). */
  logger?: Logger;

  /**
   * Pricing model for cost estimation in the trace report.
   * Prices are per 1,000 tokens.
   *
   * @example
   * ```ts
   * pricing: { inputPricePer1K: 0.0025, outputPricePer1K: 0.01 }
   * ```
   */
  pricing?: {
    inputPricePer1K: number;
    outputPricePer1K: number;
  };
}

/**
 * TraceLogger — records the agent's execution trajectory and generates
 * a self-contained HTML report per session.
 *
 * Implements AgentHooks so it can be plugged directly into an Agent:
 *
 * ```ts
 * const traceLogger = new TraceLogger({ sessionId: "my-session" });
 * const agent = new ReActAgent({
 *   llm: provider,
 *   hooks: traceLogger,  // <-- hooks in as the observer
 * });
 * const answer = await agent.run("...");
 * traceLogger.flush(); // writes .kagent-traces/my-session.html
 * ```
 *
 * The HTML report is a standalone file with no external dependencies —
 * all CSS and JS are inlined. It shows a vertical timeline of all events
 * (LLM calls, tool executions, thoughts, errors) with expandable details
 * for each.
 */
export class TraceLogger implements AgentHooks {
  private events: AgentTraceEvent[] = [];
  private eventId = 0;
  private sessionId: string;
  private outputDir: string;
  private agentLabel: string;
  private modelName: string;
  private startTime: number;
  private logger: Logger;
  private pricing?: { inputPricePer1K: number; outputPricePer1K: number };

  // ── Session-level counters for summary stats ──
  private llmCallCount = 0;
  private toolCallCount = 0;
  private totalPromptTokens = 0;
  private totalCompletionTokens = 0;

  // ── Sub-agent spawn counter (links spawn events to child traces) ──
  private spawnSeq = 0;

  // ── Sub-agent trace embedding ──
  private parent?: TraceLogger;
  private subTraceId: string = ""; // set on child traces to link with parent events
  private childrenTraces: Array<{
    traceId: string;
    agentLabel: string;
    events: AgentTraceEvent[];
    sessionCounters: { llmCalls: number; toolCalls: number; promptTokens: number; completionTokens: number };
    startTime: number;
    endTime: number;
    modelName: string;
  }> = [];

  constructor(config?: TraceLoggerConfig) {
    const ts = Date.now();
    const rand = Math.random().toString(36).slice(2, 6);
    this.sessionId =
      config?.sessionId ?? `trace-${ts}-${rand}`;
    this.outputDir = path.resolve(config?.outputDir ?? ".kagent-traces");
    this.agentLabel = config?.agentLabel ?? "Agent";
    this.modelName = config?.modelName ?? "unknown";
    this.logger = config?.logger ?? new ConsoleLogger();
    this.pricing = config?.pricing;
    this.startTime = ts;
  }

  // ─── Public API ──────────────────────────────────────────────────────────

  /**
   * Get the session identifier for this trace.
   */
  getSessionId(): string {
    return this.sessionId;
  }

  /**
   * Get all recorded events.
   */
  getEvents(): AgentTraceEvent[] {
    return [...this.events];
  }

  /**
   * Create a child TraceLogger for a sub-agent run.
   *
   * The child trace writes to a separate HTML file with a nested session ID
   * (`{parentId}__sub_{name}_{runId}`) so each sub-agent gets its own
   * isolated timeline. Inherits the parent's output directory, model name,
   * logger, and pricing configuration.
   *
   * **Usage** — pass as a factory in AgentConfig:
   * ```ts
   * const mainTrace = new TraceLogger({ sessionId: "main" });
   * const agent = new ReActAgent({
   *   llm: provider,
   *   hooks: mainTrace,
   *   subAgentHooks: (name, runId) => mainTrace.createChildTrace(name, runId),
   *   subAgentsDir: "./subagents",
   * });
   * ```
   *
   * @param name  The sub-agent definition name.
   * @param runId The unique run ID generated by SubAgentManager.
   * @returns A new TraceLogger for the sub-agent's execution.
   */
  createChildTrace(name: string, runId: string): TraceLogger {
    const child = new TraceLogger({
      sessionId: runId,
      outputDir: this.outputDir,
      agentLabel: `${this.agentLabel} › ${name}`,
      modelName: this.modelName,
      logger: this.logger,
      pricing: this.pricing,
    });
    // Link child to parent — when the sub-agent finishes, its events
    // are serialised into the parent trace instead of a separate file.
    child.parent = this;
    child.subTraceId = runId;
    return child;
  }

  /**
   * Flush the trace to an HTML file on disk.
   * Creates the output directory if it doesn't exist.
   *
   * @returns The absolute path to the generated HTML file.
   */
  flush(): string {
    try {
      const html = this.generateHTML();
      fs.mkdirSync(this.outputDir, { recursive: true });
      const filePath = path.join(this.outputDir, `${this.sessionId}.html`);
      fs.writeFileSync(filePath, html, "utf-8");
      this.logger.info("Trace", `Saved session trace → ${filePath}`);
      return filePath;
    } catch (err: unknown) {
      const message = err instanceof Error ? err.message : String(err);
      this.logger.error("Trace", `Failed to write trace file: ${message}`);
      return "";
    }
  }

  // ─── AgentHooks Implementation ─────────────────────────────────────────

  onLLMStart(messages: MessageData[], tools: Tool[]): void {
    this.llmCallCount++;
    this.addEvent("llm_start", `LLM Call #${this.llmCallCount}`, {
      messageCount: messages.length,
      toolCount: tools.length,
      messages: messages.map((m) => ({
        role: m.role,
        content: m.content,
        tool_calls: m.tool_calls,
        tool_call_id: m.tool_call_id,
        name: m.name,
      })),
      tools: tools.map((t) => ({
        name: t.name,
        description: t.description,
      })),
    });
  }

  onLLMEnd(response: LLMResponse): void {
    if (response.usage) {
      this.totalPromptTokens += response.usage.prompt_tokens;
      this.totalCompletionTokens += response.usage.completion_tokens;
    }
    this.addEvent("llm_end", "LLM Response", {
      content: response.content,
      tool_calls: response.tool_calls,
      usage: response.usage,
    });
  }

  onLLMError(error: LLMNetworkError): void {
    this.addEvent("llm_error", "LLM Error", {
      cause: error.cause,
      message: error.message,
    });
    // Push to parent trace if this is a sub-agent, otherwise flush to file.
    if (this.parent) {
      this.parent.addChildTrace({
        traceId: this.subTraceId,
        agentLabel: this.agentLabel,
        events: this.events,
        sessionCounters: {
          llmCalls: this.llmCallCount,
          toolCalls: this.toolCallCount,
          promptTokens: this.totalPromptTokens,
          completionTokens: this.totalCompletionTokens,
        },
        startTime: this.startTime,
        endTime: Date.now(),
        modelName: this.modelName,
      });
    } else {
      this.flush();
    }
  }

  onToolStart(toolName: string, args: Record<string, unknown>, toolCallId?: string): void {
    this.toolCallCount++;
    this.addEvent("tool_start", `Tool: ${toolName}`, {
      toolName,
      toolCallId,
      args,
    });

    // For spawn_subagent, emit a dedicated subagent_spawn event so the
    // timeline clearly delineates where work is delegated to a sub-agent.
    if (toolName === "spawn_subagent" && args.name) {
      const seq = ++this.spawnSeq;
      const subInput = (args.input ?? args.task ?? "") as string;
      this.addEvent("subagent_spawn", `Sub-Agent: ${args.name}`, {
        subAgentName: args.name,
        input: subInput,
        spawnSeq: seq,
      });
    }
  }

  onToolEnd(toolName: string, result: string, toolCallId?: string): void {
    this.addEvent("tool_end", `Tool Result: ${toolName}`, {
      toolName,
      toolCallId,
      result: result.length > 2000 ? result.slice(0, 2000) + "\n... (truncated)" : result,
      resultLength: result.length,
    });

    // For spawn_subagent results, emit a subagent_result event with the
    // wrapped output so the timeline shows sub-agent completion clearly.
    if (toolName === "spawn_subagent") {
      this.addEvent("subagent_result", `Sub-Agent Result`, {
        toolName,
        toolCallId,
        result: result.length > 4000 ? result.slice(0, 4000) + "\n... (truncated)" : result,
        resultLength: result.length,
      });
    }
  }

  onToolError(toolName: string, error: string, toolCallId?: string): void {
    this.addEvent("tool_error", `Tool Error: ${toolName}`, {
      toolName,
      toolCallId,
      error,
    });
  }

  onThought(thought: string): void {
    this.addEvent("thought", "Thought", { thought });
  }

  onPlanCreated(plan: string[]): void {
    this.addEvent("plan_created", "Plan Created", { plan });
  }

  onPlanRevised(plan: string[]): void {
    this.addEvent("plan_revised", "Plan Revised", { plan });
  }

  onFinish(answer: string): void {
    this.addEvent("finish", "Final Answer", { answer });

    if (this.parent) {
      // Sub-agent: push trace data into the parent instead of writing a file.
      this.parent.addChildTrace({
        traceId: this.subTraceId,
        agentLabel: this.agentLabel,
        events: this.events,
        sessionCounters: {
          llmCalls: this.llmCallCount,
          toolCalls: this.toolCallCount,
          promptTokens: this.totalPromptTokens,
          completionTokens: this.totalCompletionTokens,
        },
        startTime: this.startTime,
        endTime: Date.now(),
        modelName: this.modelName,
      });
    } else {
      // Main agent: flush to file.
      this.flush();
    }
  }

  /** Drop oldest child traces once this ceiling is reached (prevents OOM). */
  private static MAX_CHILD_TRACES = 20;

  /** Called by a child trace to deposit its events into this (parent) trace. */
  private addChildTrace(child: TraceLogger["childrenTraces"][number]): void {
    if (this.childrenTraces.length >= TraceLogger.MAX_CHILD_TRACES) {
      this.childrenTraces.shift(); // drop oldest
    }
    this.childrenTraces.push(child);
  }

  // ─── Private Helpers ─────────────────────────────────────────────────────

  /** Drop oldest events once this ceiling is reached (prevents OOM). */
  private static MAX_EVENTS = 500;

  private addEvent(
    type: AgentTraceEventType,
    label: string,
    data: Record<string, unknown>,
  ): void {
    if (this.events.length >= TraceLogger.MAX_EVENTS) {
      this.events.shift(); // drop oldest
    }
    this.events.push({
      id: ++this.eventId,
      timestamp: new Date().toISOString(),
      type,
      label,
      data,
    });
  }

  // ─── HTML Generation ────────────────────────────────────────────────────

  private generateHTML(): string {
    const duration = ((Date.now() - this.startTime) / 1000).toFixed(1);
    const eventCards = this.events.map((e) => this.renderEventCard(e)).join("\n");

    // ── Summary stats ──────────────────────────────────────────────────
    const totalTokens = this.totalPromptTokens + this.totalCompletionTokens;
    const costStr = this.pricing
      ? ` | 💰 ${this.fmtCost(this.totalPromptTokens, this.totalCompletionTokens)}`
      : "";

    return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Session Trace — ${this.sessionId}</title>
<style>
  *, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }
  body {
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
    background: #0d1117; color: #c9d1d9; line-height: 1.6; padding: 24px;
  }
  .container { max-width: 960px; margin: 0 auto; }

  /* ── Header ── */
  .header {
    background: linear-gradient(135deg, #161b22, #1c2333);
    border: 1px solid #30363d; border-radius: 12px; padding: 24px 28px;
    margin-bottom: 20px;
  }
  .header h1 { font-size: 20px; margin-bottom: 8px; display: flex; align-items: center; gap: 10px; }
  .header h1 span { background: #238636; color: #fff; font-size: 11px; padding: 2px 8px; border-radius: 20px; }
  .header .meta { display: flex; flex-wrap: wrap; gap: 16px; font-size: 13px; color: #8b949e; }
  .header .meta .item { display: flex; align-items: center; gap: 4px; }
  .header .meta .item strong { color: #c9d1d9; }

  /* ── Summary Stats Bar ── */
  .summary {
    background: #161b22; border: 1px solid #30363d; border-radius: 10px;
    padding: 14px 20px; margin-bottom: 24px;
    display: flex; flex-wrap: wrap; gap: 20px; font-size: 13px;
  }
  .summary .stat { display: flex; align-items: center; gap: 6px; }
  .summary .stat .val { color: #e6edf3; font-weight: 600; font-family: monospace; }
  .summary .stat .lbl { color: #8b949e; }

  /* ── Timeline ── */
  .timeline { position: relative; padding-left: 36px; }
  .timeline::before {
    content: ''; position: absolute; left: 14px; top: 8px; bottom: 8px;
    width: 2px; background: #21262d;
  }

  /* ── Event Card ── */
  .event { position: relative; margin-bottom: 12px; }
  .event-dot {
    position: absolute; left: -26px; top: 14px; width: 12px; height: 12px;
    border-radius: 50%; border: 2px solid #30363d; background: #0d1117; z-index: 1;
  }
  .event-body {
    background: #161b22; border: 1px solid #30363d; border-radius: 8px;
    padding: 12px 16px; cursor: pointer; transition: border-color .15s;
  }
  .event-body:hover { border-color: #58a6ff; }
  .event-header {
    display: flex; align-items: center; gap: 8px; font-size: 13px;
    user-select: none;
  }
  .event-header .icon { font-size: 16px; flex-shrink: 0; }
  .event-header .label { flex: 1; font-weight: 600; color: #e6edf3; }
  .event-header .badge {
    font-size: 11px; padding: 1px 7px; border-radius: 10px;
    font-family: monospace; white-space: nowrap;
  }
  .badge-tokens { background: #1a2332; color: #79c0ff; }
  .badge-cost { background: #1a2f1a; color: #3fb950; }
  .event-header .time { color: #8b949e; font-size: 11px; font-family: monospace; }
  .event-header .toggle { color: #8b949e; font-size: 12px; }
  .event-detail {
    display: none; margin-top: 10px; border-top: 1px solid #21262d;
    padding-top: 10px; font-size: 13px;
  }
  .event.open .event-detail { display: block; }
  .event.open .toggle { transform: rotate(90deg); }

  /* ── Detail Blocks ── */
  .detail-section { margin-bottom: 10px; }
  .detail-section:last-child { margin-bottom: 0; }
  .detail-section h4 { font-size: 11px; text-transform: uppercase; color: #8b949e; margin-bottom: 4px; letter-spacing: .5px; }
  pre {
    background: #0d1117; border: 1px solid #21262d; border-radius: 6px;
    padding: 10px 12px; font-family: 'JetBrains Mono', 'Fira Code', monospace;
    font-size: 12px; overflow-x: auto; white-space: pre-wrap; word-break: break-all;
    color: #e6edf3; max-height: 400px; overflow-y: auto;
  }
  pre .key { color: #79c0ff; }
  pre .string { color: #a5d6ff; }
  pre .number { color: #79c0ff; }
  pre .null { color: #d2a8ff; }
  pre .bool { color: #d2a8ff; }

  /* ── Event-type color accents ── */
  .event-type-llm_start .event-dot { border-color: #58a6ff; background: #1f6feb; }
  .event-type-llm_end .event-dot { border-color: #58a6ff; background: #1f6feb; }
  .event-type-llm_error .event-dot { border-color: #f85149; background: #da3633; }
  .event-type-tool_start .event-dot { border-color: #d29922; background: #9e6a03; }
  .event-type-tool_end .event-dot { border-color: #3fb950; background: #238636; }
  .event-type-tool_error .event-dot { border-color: #f85149; background: #da3633; }
  .event-type-thought .event-dot { border-color: #bc8cff; background: #8957e5; }
  .event-type-plan_created .event-dot { border-color: #79c0ff; background: #1f6feb; }
  .event-type-plan_revised .event-dot { border-color: #f0883e; background: #bd6200; }
  .event-type-finish .event-dot { border-color: #3fb950; background: #238636; }
  .event-type-subagent_spawn .event-dot { border-color: #79c0ff; background: #1f6feb; }
  .event-type-subagent_result .event-dot { border-color: #3fb950; background: #238636; }

  .event-type-llm_error .event-body { border-color: #f85149; }
  .event-type-tool_error .event-body { border-color: #f85149; }

  /* ── Plan steps list ── */
  ol.plan-steps { padding-left: 20px; margin: 4px 0; }
  ol.plan-steps li { margin-bottom: 2px; color: #e6edf3; }

  /* ── Tool call args table ── */
  .kv-table { width: 100%; border-collapse: collapse; font-size: 12px; }
  .kv-table th, .kv-table td {
    text-align: left; padding: 4px 8px; border: 1px solid #21262d;
  }
  .kv-table th { background: #0d1117; color: #8b949e; font-weight: 500; white-space: nowrap; }

  /* ── Child Trace (Sub-Agent) ── */
  .child-trace {
    margin-top: 16px; border: 1px solid #30363d; border-radius: 10px;
    background: #161b22; overflow: hidden;
  }
  .child-trace-header {
    display: flex; align-items: center; gap: 8px;
    padding: 12px 16px; cursor: pointer; user-select: none;
    background: #1c2333; border-bottom: 1px solid #30363d;
  }
  .child-trace-header:hover { background: #21262d; }
  .child-trace-header .icon { font-size: 18px; }
  .child-trace-header .label { flex: 1; font-weight: 600; color: #79c0ff; }
  .child-trace-header .badge {
    font-size: 11px; padding: 1px 7px; border-radius: 10px;
    background: #1a2332; color: #8b949e; font-family: monospace;
  }
  .child-trace-header .time { color: #8b949e; font-size: 13px; }
  .child-trace-header .toggle { color: #8b949e; font-size: 12px; transition: transform .15s; }
  .child-trace.open .child-trace-header .toggle { transform: rotate(90deg); }
  .child-trace-body { display: none; padding: 0 16px 16px; }
  .child-trace.open .child-trace-body { display: block; }

  @media (max-width: 640px) {
    body { padding: 12px; }
    .timeline { padding-left: 28px; }
    .summary { gap: 12px; }
  }
</style>
</head>
<body>
<div class="container">

  <div class="header">
    <h1>🤖 <span>TRACE</span> ${this.escapeHtml(this.agentLabel)}</h1>
    <div class="meta">
      <span class="item"><strong>Session:</strong> ${this.escapeHtml(this.sessionId)}</span>
      <span class="item"><strong>Model:</strong> ${this.escapeHtml(this.modelName)}</span>
      <span class="item"><strong>Duration:</strong> ${duration}s</span>
      <span class="item"><strong>Events:</strong> ${this.events.length}</span>
      <span class="item"><strong>Generated:</strong> ${new Date().toLocaleString("zh-CN", { hour12: false })}</span>
    </div>
  </div>

  <div class="summary">
    <span class="stat"><span class="lbl">LLM Calls:</span><span class="val">${this.llmCallCount}</span></span>
    <span class="stat"><span class="lbl">Tool Calls:</span><span class="val">${this.toolCallCount}</span></span>
    <span class="stat"><span class="lbl">Tokens:</span><span class="val">${this.fmtNum(totalTokens)}</span></span>
    <span class="stat"><span class="lbl">In / Out:</span><span class="val">${this.fmtNum(this.totalPromptTokens)} / ${this.fmtNum(this.totalCompletionTokens)}</span></span>${costStr}
  </div>

  <div class="timeline">
${eventCards}
  </div>
${this.childrenTraces.length > 0 ? this.renderChildTraces() : ""}

</div>
<script>
  document.querySelectorAll('.event-body').forEach(el => {
    el.addEventListener('click', () => {
      el.parentElement.classList.toggle('open');
    });
  });
  // Auto-open error events and the final answer
  document.querySelectorAll('.event-type-llm_error, .event-type-tool_error, .event-type-finish, .event-type-plan_created, .event-type-plan_revised, .event-type-subagent_spawn, .event-type-subagent_result')
    .forEach(el => el.classList.add('open'));
</script>
</body>
</html>`;
  }

  /** Render collapsible child-trace sections below the main timeline. */
  private renderChildTraces(): string {
    return this.childrenTraces.map((child, i) => {
      const duration = ((child.endTime - child.startTime) / 1000).toFixed(1);
      const totalTokens = child.sessionCounters.promptTokens + child.sessionCounters.completionTokens;
      const eventCards = child.events.map((e) => this.renderEventCard(e)).join("\n");
      return `
  <div class="child-trace" id="child-trace-${i}">
    <div class="child-trace-header" onclick="document.getElementById('child-trace-${i}').classList.toggle('open')">
      <span class="icon">🤖</span>
      <span class="label">${this.escapeHtml(child.agentLabel)}</span>
      <span class="badge">${child.events.length} events</span>
      <span class="badge">${this.fmtNum(totalTokens)} tok</span>
      <span class="time">${duration}s</span>
      <span class="toggle">▶</span>
    </div>
    <div class="child-trace-body">
      <div class="summary" style="margin-top:12px">
        <span class="stat"><span class="lbl">LLM Calls:</span><span class="val">${child.sessionCounters.llmCalls}</span></span>
        <span class="stat"><span class="lbl">Tool Calls:</span><span class="val">${child.sessionCounters.toolCalls}</span></span>
        <span class="stat"><span class="lbl">Tokens:</span><span class="val">${this.fmtNum(totalTokens)}</span></span>
        <span class="stat"><span class="lbl">In / Out:</span><span class="val">${this.fmtNum(child.sessionCounters.promptTokens)} / ${this.fmtNum(child.sessionCounters.completionTokens)}</span></span>
      </div>
      <div class="timeline" style="margin-top:12px">
${eventCards}
      </div>
    </div>
  </div>`;
    }).join("\n");
  }

  private renderEventCard(event: AgentTraceEvent): string {
    const cls = `event event-type-${event.type}`;
    const time = new Date(event.timestamp).toLocaleTimeString("en-US", { hour12: false });
    const icon = this.eventIcon(event.type);
    let headerBadge = ""; // inline stat badge shown on the card header
    let detail = "";

    switch (event.type) {
      case "llm_start": {
        const msgs = event.data.messages as Array<{ role: string; content: string }> | undefined;
        const tools = event.data.tools as Array<{ name: string; description: string }> | undefined;
        detail = `<div class="detail-section">
          <h4>Messages (${msgs?.length ?? 0})</h4>
          <pre>${this.syntaxHighlight(JSON.stringify(msgs ?? [], null, 2))}</pre>
        </div>`;
        if (tools && tools.length > 0) {
          detail += `<div class="detail-section">
            <h4>Available Tools (${tools.length})</h4>
            <pre>${this.syntaxHighlight(JSON.stringify(tools, null, 2))}</pre>
          </div>`;
        }
        break;
      }
      case "llm_end": {
        detail = `<div class="detail-section">
          <h4>Content</h4>
          <pre>${this.escapeHtml(String(event.data.content ?? ""))}</pre>
        </div>`;
        const tc = event.data.tool_calls as Array<{ function: { name: string; arguments: string } }> | undefined;
        if (tc && tc.length > 0) {
          detail += `<div class="detail-section">
            <h4>Tool Calls</h4>
            <pre>${this.syntaxHighlight(JSON.stringify(tc, null, 2))}</pre>
          </div>`;
        }
        const usage = event.data.usage as { prompt_tokens?: number; completion_tokens?: number; total_tokens?: number } | undefined;
        if (usage) {
          // Inline badge for the card header
          const pts = usage.prompt_tokens ?? 0;
          const cts = usage.completion_tokens ?? 0;
          const tokensBadge = `<span class="badge badge-tokens">in ${this.fmtNum(pts)} / out ${this.fmtNum(cts)} tok</span>`;
          let costBadge = "";
          if (this.pricing) {
            const cost = (pts / 1000) * this.pricing.inputPricePer1K + (cts / 1000) * this.pricing.outputPricePer1K;
            costBadge = `<span class="badge badge-cost">$${cost.toFixed(4)}</span>`;
          }
          headerBadge = tokensBadge + costBadge;

          detail += `<div class="detail-section">
            <h4>Usage</h4>
            <table class="kv-table"><tr>
              <th>Prompt</th><th>Completion</th><th>Total</th>
            </tr><tr>
              <td>${usage.prompt_tokens ?? "—"}</td>
              <td>${usage.completion_tokens ?? "—"}</td>
              <td>${usage.total_tokens ?? "—"}</td>
            </tr></table>
          </div>`;
        }
        break;
      }
      case "llm_error": {
        detail = `<div class="detail-section">
          <h4>Error (${this.escapeHtml(String(event.data.cause ?? ""))})</h4>
          <pre>${this.escapeHtml(String(event.data.message ?? ""))}</pre>
        </div>`;
        break;
      }
      case "tool_start": {
        const tblRows = Object.entries(event.data.args as Record<string, unknown> ?? {})
          .map(([k, v]) => `<tr><th>${this.escapeHtml(k)}</th><td><pre style="margin:0;padding:4px;background:none;border:none;max-height:200px">${this.escapeHtml(JSON.stringify(v, null, 2))}</pre></td></tr>`)
          .join("");
        detail = `<div class="detail-section">
          <h4>Arguments</h4>
          <table class="kv-table">${tblRows}</table>
        </div>`;
        break;
      }
      case "tool_end": {
        detail = `<div class="detail-section">
          <h4>Result (${event.data.resultLength} chars)</h4>
          <pre>${this.escapeHtml(String(event.data.result ?? ""))}</pre>
        </div>`;
        break;
      }
      case "tool_error": {
        detail = `<div class="detail-section">
          <h4>Error</h4>
          <pre>${this.escapeHtml(String(event.data.error ?? ""))}</pre>
        </div>`;
        break;
      }
      case "thought": {
        detail = `<div class="detail-section">
          <pre>${this.escapeHtml(String(event.data.thought ?? ""))}</pre>
        </div>`;
        break;
      }
      case "plan_created":
      case "plan_revised": {
        const plan = event.data.plan as string[] | undefined;
        if (plan && plan.length > 0) {
          detail = `<div class="detail-section">
            <ol class="plan-steps">${plan.map((s) => `<li>${this.escapeHtml(s)}</li>`).join("")}</ol>
          </div>`;
        }
        break;
      }
      case "finish": {
        detail = `<div class="detail-section">
          <pre>${this.escapeHtml(String(event.data.answer ?? ""))}</pre>
        </div>`;
        break;
      }
      case "subagent_spawn": {
        const subName = event.data.subAgentName as string | undefined;
        const subInput = event.data.input as string | undefined;
        // Link by spawn order: childrenTraces are added in spawn order,
        // so spawnSeq-1 = childrenTraces index.
        const spawnSeq = event.data.spawnSeq as number | undefined;
        const childIdx = (spawnSeq !== undefined && spawnSeq > 0 && spawnSeq <= this.childrenTraces.length)
          ? spawnSeq - 1
          : (this.childrenTraces.length > 0 ? this.childrenTraces.length - 1 : null);
        detail = `<div class="detail-section">
          <h4>Sub-Agent: ${this.escapeHtml(subName ?? "unknown")}</h4>
        </div>`;
        if (subInput) {
          detail += `<div class="detail-section">
            <h4>Task</h4>
            <pre>${this.escapeHtml(subInput)}</pre>
          </div>`;
        }
        if (childIdx !== null && childIdx < this.childrenTraces.length) {
          detail += `<div class="detail-section">
            <a href="#child-trace-${childIdx}" style="color:#58a6ff">📋 View sub-agent trace ↓</a>
          </div>`;
        }
        break;
      }
      case "subagent_result": {
        const childIdx = this.childrenTraces.length > 0 ? this.childrenTraces.length - 1 : null;
        detail = `<div class="detail-section">
          <h4>Sub-Agent Output (${event.data.resultLength ?? 0} chars)</h4>
          <pre>${this.escapeHtml(String(event.data.result ?? ""))}</pre>
        </div>`;
        if (childIdx !== null) {
          detail += `<div class="detail-section">
            <a href="#child-trace-${childIdx}" style="color:#58a6ff">📋 View full sub-agent trace ↓</a>
          </div>`;
        }
        break;
      }
    }

    return `    <div class="${cls}">
      <div class="event-dot"></div>
      <div class="event-body">
        <div class="event-header">
          <span class="icon">${icon}</span>
          <span class="label">${this.escapeHtml(event.label)}</span>
          ${headerBadge}
          <span class="time">${time}</span>
          <span class="toggle">▶</span>
        </div>
        <div class="event-detail">${detail}</div>
      </div>
    </div>`;
  }

  /** Format large numbers with K/M suffix. */
  private fmtNum(n: number): string {
    if (n >= 1_000_000) return (n / 1_000_000).toFixed(1) + "M";
    if (n >= 1_000) return (n / 1_000).toFixed(1) + "K";
    return String(n);
  }

  /** Format cost summary string for the summary bar. */
  private fmtCost(promptTokens: number, completionTokens: number): string {
    if (!this.pricing) return "";
    const cost =
      (promptTokens / 1000) * this.pricing.inputPricePer1K +
      (completionTokens / 1000) * this.pricing.outputPricePer1K;
    return `<span class="stat"><span class="lbl">Cost:</span><span class="val">$${cost.toFixed(4)}</span></span>`;
  }

  private eventIcon(type: AgentTraceEventType): string {
    switch (type) {
      case "llm_start": return "📤";
      case "llm_end": return "📥";
      case "llm_error": return "❌";
      case "tool_start": return "🔧";
      case "tool_end": return "✅";
      case "tool_error": return "⚠️";
      case "thought": return "💭";
      case "plan_created": return "📋";
      case "plan_revised": return "🔄";
      case "finish": return "🏁";
      case "subagent_spawn": return "🚀";
      case "subagent_result": return "📬";
    }
  }

  private escapeHtml(text: string): string {
    return text
      .replace(/&/g, "&amp;")
      .replace(/</g, "&lt;")
      .replace(/>/g, "&gt;")
      .replace(/"/g, "&quot;");
  }

  private syntaxHighlight(json: string): string {
    // Escape HTML-dangerous characters before highlighting (keep " for the
    // regex below). Prevents XSS when LLM-generated content contains
    // literal <script> tags in code-review output.
    const safe = json
      .replace(/&/g, "&amp;")
      .replace(/</g, "&lt;")
      .replace(/>/g, "&gt;");
    return safe.replace(
      /("(?:[^"\\]|\\.)*")\s*:/g,
      '<span class="key">$1</span>:',
    ).replace(
      /:\s*("(?:[^"\\]|\\.)*")/g,
      ': <span class="string">$1</span>',
    ).replace(
      /:\s*(\d+(?:\.\d+)?)/g,
      ': <span class="number">$1</span>',
    ).replace(
      /:\s*(true|false)/g,
      ': <span class="bool">$1</span>',
    ).replace(
      /:\s*(null)/g,
      ': <span class="null">$1</span>',
    );
  }
}
